### ISSUE TITLE
Editor crashes while loading gdextension

### ISSUE THREAD

**Issue by fpdotmonkey** [godot-rust/gdextension#26] opened 2022-11-20 14:14 UTC
I'm trying to get a basic Hello World sort of extension running, but I'm getting this error when launching my project from `4.0.beta5.official.89a33d28f`.

```
Initialize GDExtension interface: Godot Engine v4.0.beta5.official
ERROR: Index p_constructor = 6 is out of bounds ((int)construct_data[p_type].size() = 6).
   at: get_ptr_constructor (core/variant/variant_construct.cpp:298)
thread '<unnamed>' panicked at 'failed to load GDExtension function `quaternion_from_euler_yxz`', /home/fp/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/522dda7/godot-ffi/../target/godot-gen/sys/central.rs:1:54858
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

I do not get this error with the same project on godot `4.0.beta.custom_build.01ae26d31` (the same commit as beta 4).  However, this build doesn't seem to actually load the extension.

I have the same `<extension>.gdextension`, `extension_list.cfg`, and `lib.rs` with the exception of different names for the stuff that's mine and I've flattened the project structure so there's no `godot/` or `rust` folders, e.g. `cargo.toml` and `godot.project` are in the same directory.  I've changed all the relevant paths in the previously mentioned files to reflect this.

I reckon I must be doing something wrong, but as far as I can see from the instructions, I can't find what.

**Comment by fpdotmonkey** [comment] 2022-11-20 14:18
Sorry I realized I hadn't rebuilt after running `cargo update` after sending this, so I did, but the crash persists on beta 5

```
Initialize GDExtension interface: Godot Engine v4.0.beta5.official
Godot Engine v4.0.beta5.official.89a33d28f - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV VEGAM
libdbus-1.so: cannot open shared object file: No such file or directory
libdbus-1.so: cannot open shared object file: No such file or directory

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta5.official (89a33d28f00fec579184fb7193790d40aa09b45b)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fbe1ba49520] (??:0)
[2] /home/fp/Downloads/Godot_v4.0-beta5_linux.x86_64() [0x429d7e8] (??:0)
[3] /home/fp/Downloads/Godot_v4.0-beta5_linux.x86_64() [0x42d284d] (??:0)
[4] /home/fp/projects/word-game/target/debug/libword_game.so(+0x1db4c) [0x7fbe16294b4c] (??:0)
[5] /home/fp/projects/word-game/target/debug/libword_game.so(+0x1d460) [0x7fbe16294460] (??:0)
[6] /home/fp/projects/word-game/target/debug/libword_game.so(+0x1c4fb) [0x7fbe162934fb] (??:0)
[7] /home/fp/projects/word-game/target/debug/libword_game.so(+0x1c6bb) [0x7fbe162936bb] (??:0)
[8] /home/fp/projects/word-game/target/debug/libword_game.so(+0x1c46f) [0x7fbe1629346f] (??:0)
[9] /home/fp/Downloads/Godot_v4.0-beta5_linux.x86_64() [0x431837b] (??:0)
[10] /home/fp/Downloads/Godot_v4.0-beta5_linux.x86_64() [0xda8233] (??:0)
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fbe1ba30d90] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fbe1ba30e40] (??:0)
[13] /home/fp/Downloads/Godot_v4.0-beta5_linux.x86_64() [0xdbe18e] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Comment by Bromeon** [comment] 2022-11-20 15:12
Thanks for reporting, this is a duplicate of #25.

**Closed by Bromeon** 2022-11-20 15:12 UTC
