### ISSUE TITLE
Godot version parsing fails for nix package

### ISSUE THREAD

**Issue by RobWalt** [godot-rust/gdextension#148] opened 2023-03-06 15:57 UTC
I'm using godot on NixOS. I have to use the version of godot on the unstable channel of nixpkgs since the version on the stable channel crashes on startup. This is a link to it

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=godot_4

When I run `godot --version` I get `4.0.stable.custom_build`. This is also fine and everything works well. But when I try to use `gdextension-rust`, then I can't compile the code because the build fails because of the version parsing. The reason is, that there is no hash after the `...custom_build` part of the version. This is a requirement of the regex defined here 

https://github.com/godot-rust/gdextension/blob/master/godot-codegen/src/godot_version.rs#L33

I wanted to ask if we can relax the constraints of the checks there a bit and include `... |official|custom_build` at the end of the regex. Is the hash needed anywhere in the code?

**Comment by Bromeon** [comment] 2023-03-06 16:13
Duplicate of #118. There was some discussion in that thread, including why I think requiring a version is important.

Could you share your thoughts on that there? Then we have everything in a central place 🙂

**Closed by Bromeon** 2023-03-06 16:13 UTC
